### ISSUE TITLE
Projects: Parity with Projects (classic) Milestone 2

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#483]
### Summary

In order to help teams migrate over from projects classic, we have a number of areas where we are working towards feature parity. Following on from our work [last quarter](https://github.com/github/roadmap/issues/287), in progress for this quarter are:

- [x] Ability to delete a project
- [x] Add projects to teams pages for quick access
- [x] Show issue/PR item number in the title

**Comment by ankneis** [comment]
🚢 Partially shipped!

**Comment by ankneis** [comment]
🚢 All of these features have shipped:

- Issue/PR numbers: https://github.blog/changelog/2022-09-02-the-new-github-issues-september-2nd-update/
- Linking projects to teams: https://github.blog/changelog/2022-09-27-the-new-github-issues-september-27th-update/
