### ISSUE TITLE
Projects: Parity with Projects (classic) Milestone 3

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#613]
### Summary

In order to help teams migrate over from projects classic, we have a number of areas where we are working towards feature parity. In this quarter, we hope to address the following:

- [ ] Project events are included in issue / pull request timelines
- [ ] Ability to inherit permissions from a linked repo; improved creation experience from the repo projects index
- [ ] Activity history for a project
- [ ] Ability to deep link to an issue within a project

**Comment by ankneis** [comment]
🚢 This has shipped: https://github.blog/changelog/2023-01-12-github-issues-january-12th-update
