### ISSUE TITLE
🚢 This has shipped: https://github.blog/changelog/2024-01-18-github-issues-projects-project-status-updates-issues-side-panel/

### ISSUE THREAD

**Issue by kingabnt** [github/roadmap#941]
🚢 This has shipped: https://github.blog/changelog/2024-01-18-github-issues-projects-project-status-updates-issues-side-panel/

Leaving open to track for GHES release!

_Originally posted by @ankneis in https://github.com/github/roadmap/issues/830#issuecomment-1904750480_
            
```[tasklist]
### Tasks
- [ ] https://github.com/github/roadmap/issues/918
- [ ] https://github.com/github/roadmap/issues/820
- [ ] https://github.com/github/roadmap/issues/804
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/roadmap/issues/825
- [ ] https://github.com/github/roadmap/issues/918
- [ ] https://github.com/github/roadmap/issues/850
- [ ] https://github.com/github/roadmap/issues/851
- [ ] https://github.com/github/roadmap/issues/634
```
