### ISSUE TITLE
https://github.com/github/roadmap/issues/933#issue-2159789726

### ISSUE THREAD

**Issue by dnabookofficiaal** [github/roadmap#997]
https://github.com/github/roadmap/issues/933#issue-2159789726

_Originally posted by @dnabookofficiaal in https://github.com/github/roadmap/pull/951#pullrequestreview-2217989153_
            
```[tasklist]
### Tasks
- [x] e.g.soheil.damanafshan.com
- [x] http://tplinkwifi.net
- [x] www.apple.com
- [ ] https://github.com/github/roadmap/pull/951
- [x] www.soheildaman.com
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/roadmap/issues/830
- [ ] https://github.com/github/roadmap/pull/951
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/roadmap/issues/799
- [ ] https://github.com/github/roadmap/pull/951
- [ ] https://github.com/github/roadmap/issues/994
```
